boxplot voor NrToetscijfers
cumalikarakoc/ais-machine-learning pull request #7
Opened 2020-05-12 15:18 UTC by refaiothman

2020-05-13 07:30 UTC, cumalikarakoc requested changes

2020-05-13 07:30 UTC, cumalikarakoc commented on DataExploration/OnderwijsEenheidResultaten_Plots.R
>  ggplot(OnderwijsEenheidResultaten_df,aes(x=TeBehalenStpt)) +
ik zie geen nut om verdeling te laten zien van een feature die alleen maar 1 kardinaliteit heeft. Wij weten dus al de verdeling.

2020-06-09 18:32 UTC, refaiothman commented on DataExploration/OnderwijsEenheidResultaten_Plots.R
>  ggplot(OnderwijsEenheidResultaten_df,aes(x=TeBehalenStpt)) +
Het is al verwijderd

2020-06-09 18:36 UTC, cumalikarakoc approved these changes

2020-06-09 18:37 UTC, merged